# Pass 7: repair NSIS variable names corrupted by pass 1's hyphenation.
# All "SearchT-UI<Name>" variable identifiers become "Searcht<Name>".
s/SearchT-UIActiveMarkerExecResult/SearchtActiveMarkerExecResult/g
s/SearchT-UIActiveMarkerResult/SearchtActiveMarkerResult/g
s/SearchT-UIActualArch/SearchtActualArch/g
s/SearchT-UIAtomicFailedPath/SearchtAtomicFailedPath/g
s/SearchT-UIAtomicRemoveSucceeded/SearchtAtomicRemoveSucceeded/g
s/SearchT-UIAtomicStagingDir/SearchtAtomicStagingDir/g
s/SearchT-UIBundledUninstaller/SearchtBundledUninstaller/g
s/SearchT-UICheckResult/SearchtCheckResult/g
s/SearchT-UICloseRetries/SearchtCloseRetries/g
s/SearchT-UICurrentOutDir/SearchtCurrentOutDir/g
s/SearchT-UIInnerFailureReadResult/SearchtInnerFailureReadResult/g
s/SearchT-UIInnerFailureSummary/SearchtInnerFailureSummary/g
s/SearchT-UIInnerRootCode/SearchtInnerRootCode/g
s/SearchT-UIInstalledUninstaller/SearchtInstalledUninstaller/g
s/SearchT-UIIsUpdated/SearchtIsUpdated/g
s/SearchT-UILockerList/SearchtLockerList/g
s/SearchT-UILockerListEn/SearchtLockerListEn/g
s/SearchT-UILockerListFile/SearchtLockerListFile/g
s/SearchT-UILockerListZh/SearchtLockerListZh/g
s/SearchT-UILockerResult/SearchtLockerResult/g
s/SearchT-UIOwnedProcess/SearchtOwnedProcess/g
s/SearchT-UIRegInstallExe/SearchtRegInstallExe/g
s/SearchT-UIRegInstallLocation/SearchtRegInstallLocation/g
s/SearchT-UIRegUninstallString/SearchtRegUninstallString/g
s/SearchT-UIRegistryInstallIsValid/SearchtRegistryInstallIsValid/g
s/SearchT-UIRemoveDirResult/SearchtRemoveDirResult/g
s/SearchT-UIRemoveFirstFailedFile/SearchtRemoveFirstFailedFile/g
s/SearchT-UIRemoveFirstFailedPath/SearchtRemoveFirstFailedPath/g
s/SearchT-UIRemoveResidueCount/SearchtRemoveResidueCount/g
s/SearchT-UIRemoveResidueRoot/SearchtRemoveResidueRoot/g
s/SearchT-UIRepairLogResult/SearchtRepairLogResult/g
s/SearchT-UISamePath/SearchtSamePath/g
s/SearchT-UISessionId/SearchtSessionId/g
s/SearchT-UISessionLogPath/SearchtSessionLogPath/g
s/SearchT-UISessionLogResult/SearchtSessionLogResult/g
s/SearchT-UIStopResult/SearchtStopResult/g
s/SearchT-UIUninstallHadErrors/SearchtUninstallHadErrors/g
s/SearchT-UIUninstallLogResult/SearchtUninstallLogResult/g
s/SearchT-UIUpdatedAppExitWaitResult/SearchtUpdatedAppExitWaitResult/g
s/SearchT-UIVerifyResourceResult/SearchtVerifyResourceResult/g
